@addr = http://10.105.0.87:8080/api

GET {{addr}}/currencyCodes HTTP/1.1

###

GET {{addr}}/currency/usd?date=2024-11-08 HTTP/1.1

###

PATCH {{addr}}/currency HTTP/1.1

###

POST {{addr}}/currency/?date=2024-11-08 HTTP/1.1